apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dmce-demo-api-dotnet
patches:
  - target:
      labelSelector: namespaced-resource=yes
    patch: |-
      - op: add
        path: /metadata/namespace
        value: "cluster-1--dmce-demo-api-dotnet"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dmce-demo-api-dotnet--deployment
      spec:
        template:
          spec: 
            containers:
            - name: dmce-demo-api-dotnet
              env:
              - name: "ENVIRONMENT"
                value: "cluster-1"