apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dmce-demo-api-dotnet
images:
  - name: dmced01acr.azurecr.io/dmce_demo-api_dotnet
    newName: dmced01acr.azurecr.io/dmce_demo-api_dotnet
    newTag: 0.4.1-auth.1
patches:
  - target:
      labelSelector: namespaced-resource=yes
    patch: |-
      - op: add
        path: /metadata/namespace
        value: "cluster-1--dmce-demo-api-dotnet"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dmce-demo-api-dotnet--deployment
      spec:
        template:
          spec: 
            containers:
            - name: dmce-demo-api-dotnet
              env:
              - name: "ENVIRONMENT_NAME"
                value: "cluster-1"
              - name: "OIDC_AUDIENCE"
                value: "api://dmce_demo-api_dotnet_local-dev_2"
              - name: "OIDC_AUTHORITY"
                value: "https://sts.windows.net/679a5224-7633-461d-adce-df49fa1f2a04/"
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: dmce-demo-api-dotnet--secretproviderclass
      spec:
        parameters:
          keyvaultName: dmced01akv-c1-demoapi
          tenantId: 679a5224-7633-461d-adce-df49fa1f2a04