apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dmce-demo-api-dotnet
patches:
  - target:
      labelSelector: namespaced-resource=yes
    patch: |-
      - op: add
        path: /metadata/namespace
        value: "cluster-1--dmce-demo-api-dotnet"
patchesStrategicMerge:
  - patch.yaml