apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec: 
  targetNamespace: cluster-1--dmce-demo-api-dotnet
resources:
  - ../../base/dmce-demo-api-dotnet
patchesStrategicMerge:
  - patch.yaml