apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmce-demo-api-dotnet--deployment
spec:
  template:
    spec: 
      containers:
      - name: dmce-demo-api-dotnet
        env:
        - name: "ENVIRONMENT"
          value: "cluster-1"
