apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dmce-demo-api-dotnet
patches:
  - target:
      labelSelector: namespaced-resource=yes
    path: set-namespace.yaml
  - path: set-environment-variables.yaml