apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dmce-demo-api-dotnet
images:
  - name: dmced01acr.azurecr.io/dmce_demo-api_dotnet
    newName: dmced01acr.azurecr.io/dmce_demo-api_dotnet
    newTag: 0.4.0
patches:
  - target:
      labelSelector: namespaced-resource=yes
    path: set-namespace.yaml
  - path: set-environment-variables.yaml
  - path: set-keyvault.yaml
  